# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 528)
        MainWindow.setStyleSheet("#pushButtonDeleteAccounts, #exportProfileButton{\n"
"height: 24px;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color:  rgba(0, 0, 0, 0.12);\n"
"color: #ffffff;\n"
"font: \"Roboto\";\n"
"font-size: 20px;\n"
"padding: 5px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.414773 rgba(195, 20, 50, 255), stop:1 rgba(36, 11, 54, 255));\n"
"}\n"
"\n"
"#pushButtonDeleteAccounts::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0852273 rgba(195, 20, 50, 255), stop:1 rgba(36, 11, 54, 255));\n"
"}\n"
"#pushButtonDeleteAccounts::pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(157, 16, 40, 255), stop:0.590909 rgba(38, 12, 56, 255));\n"
"}\n"
"QDialogButtonBox,QPushButton{\n"
"height: 36px;\n"
"border: 1px solid;\n"
"border-radius: 4px;\n"
"border-color:  rgba(0, 0, 0, 0.12);\n"
"color: #6200ee;\n"
"font: \"Roboto\";\n"
"font-size: 20px;\n"
"padding: 5px\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(179, 179, 179);\n"
"}\n"
"\n"
"QListWidget{\n"
"border: none;\n"
"\n"
"}\n"
"#CreateAccountButton, #importProfileButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.409, x2:1, y2:0.477, stop:0 rgba(0, 210, 255, 255), stop:1 rgba(58, 123, 213, 255))\n"
"}\n"
"#CreateAccountButton::hover, #importProfileButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.409, x2:1, y2:0.477, stop:0 rgba(0, 210, 255, 255), stop:0.619318 rgba(58, 123, 213, 255))\n"
"}\n"
"#CreateAccountButton::pressed, #importProfileButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0113636, y1:0.409, x2:1, y2:0.477, stop:0 rgba(0, 175, 213, 255), stop:0.619318 rgba(39, 83, 144, 255))\n"
"}\n"
"#exportProfileButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.472, x2:1, y2:0.682, stop:0 rgba(17, 153, 142, 255), stop:1 rgba(56, 239, 125, 255));\n"
"}\n"
"#exportProfileButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.472, x2:1, y2:0.682, stop:0.261364 rgba(17, 153, 142, 255), stop:0.875 rgba(56, 239, 125, 255));\n"
"}\n"
"#exportProfileButton::pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.472, x2:1, y2:0.682, stop:0.352273 rgba(13, 120, 112, 255), stop:1 rgba(42, 179, 93, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.CreateAccountButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.CreateAccountButton.setFont(font)
        self.CreateAccountButton.setStyleSheet("")
        self.CreateAccountButton.setObjectName("CreateAccountButton")
        self.verticalLayout.addWidget(self.CreateAccountButton)
        self.importProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.importProfileButton.setObjectName("importProfileButton")
        self.verticalLayout.addWidget(self.importProfileButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBoxCkeckAll = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCkeckAll.setText("")
        self.checkBoxCkeckAll.setObjectName("checkBoxCkeckAll")
        self.horizontalLayout_2.addWidget(self.checkBoxCkeckAll)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonDeleteAccounts = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteAccounts.setObjectName("pushButtonDeleteAccounts")
        self.horizontalLayout_2.addWidget(self.pushButtonDeleteAccounts)
        self.exportProfileButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportProfileButton.setObjectName("exportProfileButton")
        self.horizontalLayout_2.addWidget(self.exportProfileButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionSettings)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Accounts manager"))
        self.CreateAccountButton.setText(_translate("MainWindow", "Create profile"))
        self.importProfileButton.setText(_translate("MainWindow", "Import profile"))
        self.pushButtonDeleteAccounts.setText(_translate("MainWindow", "Delete"))
        self.exportProfileButton.setText(_translate("MainWindow", "Export profiles"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
