# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\one_accout_line_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt, pyqtSignal
from PyQt5.QtGui import QPainter, QColor
from PyQt5.QtWidgets import QLineEdit, QLabel, QVBoxLayout, QWidget, QPushButton, QHBoxLayout
from qfluentwidgets import CaptionLabel, CheckBox, IconWidget, IndeterminateProgressRing, ToolButton, LineEdit, \
    PushButton


class ClickedIconWidget(IconWidget):
    icon_changed = pyqtSignal()  # Signal with a string argument for the new icon name

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMouseTracking(True)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.set_icon()

    def set_icon(self):
        # Your icon setting code here
        self.icon_changed.emit()


class ClickableLabel(QWidget):
    name_changed = pyqtSignal(str)

    def __init__(self, text, parent=None):
        super(ClickableLabel, self).__init__(parent)
        self.layout = QHBoxLayout(self)
        self.label = CaptionLabel(text)
        self.edit = LineEdit()
        self.edit.setPlaceholderText("Enter new text")
        self.ok_button = PushButton("OK")
        self.ok_button.clicked.connect(self.on_ok_clicked)
        self.layout.addWidget(self.label)
        self.layout.addWidget(self.edit)
        self.layout.addWidget(self.ok_button)
        self.edit.hide()
        self.ok_button.hide()
        self.is_editing = False

    def mousePressEvent(self, event):
        if not self.is_editing:
            self.label.hide()
            self.edit.setText(self.label.text())
            self.edit.show()
            self.ok_button.show()
            self.is_editing = True

    def on_ok_clicked(self):
        new_text = self.edit.text()
        if new_text != self.label.text():
            self.label.setText(new_text)
            self.name_changed.emit(new_text)
        self.edit.hide()
        self.ok_button.hide()
        self.label.show()
        self.is_editing = False

    def setText(self, text: str):
        self.label.setText(text)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(783, 53)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browser_icon = ClickedIconWidget(Form)
        self.browser_icon.setMinimumSize(QtCore.QSize(30, 30))
        self.browser_icon.setMouseTracking(True)
        self.browser_icon.setObjectName("browser_icon")
        self.horizontalLayout.addWidget(self.browser_icon)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CheckBox = CheckBox(Form)
        self.CheckBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBox.sizePolicy().hasHeightForWidth())
        self.CheckBox.setSizePolicy(sizePolicy)
        self.CheckBox.setMinimumSize(QtCore.QSize(29, 22))
        self.CheckBox.setMaximumSize(QtCore.QSize(22, 22))
        self.CheckBox.setText("")
        self.CheckBox.setObjectName("CheckBox")
        self.horizontalLayout.addWidget(self.CheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        # self.account_name_label = CaptionLabel(Form)
        self.account_name_label = ClickableLabel(Form)
        self.account_name_label.setObjectName("account_name_label")
        self.horizontalLayout.addWidget(self.account_name_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.running_ring = IndeterminateProgressRing(Form)
        self.running_ring.setMinimumSize(QtCore.QSize(30, 30))
        self.running_ring.setMaximumSize(QtCore.QSize(30, 30))
        self.running_ring.setObjectName("running_ring")
        self.horizontalLayout.addWidget(self.running_ring)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.settings_button = ToolButton(Form)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.account_name_label.setText(_translate("Form", "Caption label"))
